import { useState, useEffect, useCallback, useMemo } from 'react';
import { Wrench, DollarCircle, Clock, GraphUp, Search, Page, Table } from 'iconoir-react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import api from '../lib/api';
import { downloadCsv } from '../utils/csv';
import pioneerLogoPdf from '../assets/pioneer-logo-pdf.png';
import './CRMPages.css';
import './CrmSurface.css';
import './TechnicianKpi.css';

/**
 * Technician KPI — a periodic attendance/billing report brought in from an
 * external report (days present, hours, billed value, utilization/
 * productivity/efficiency), not generated by this platform. Read-only:
 * there is no "create a period" flow here on purpose — a new period lands
 * the same way this one did, via scripts/import-mechanic-kpi.js, matched
 * to the real mechanic record by their source employee code.
 *
 * Deliberately a separate page from Performance.jsx rather than a tab
 * there — that page already means something different (work-order
 * delivery/success rate per mechanic); folding this in would conflate two
 * unrelated meanings of "performance" under one heading.
 */

const band = pct => {
  if (pct == null) return { color: '#8b93a3', bg: '#f1f4f8' };
  if (pct < 60) return { color: '#c0392b', bg: '#fdeaea' };
  if (pct < 85) return { color: '#c2841c', bg: '#fcf0d9' };
  return { color: '#17734f', bg: '#ddf0e6' };
};

const fmtDate = d => d ? new Date(d).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' }) : '—';
const fmtMoney = v => v != null ? `AED ${Number(v).toLocaleString(undefined, { maximumFractionDigits: 0 })}` : '—';

export default function TechnicianKpi() {
  const [periods, setPeriods] = useState([]);
  const [selected, setSelected] = useState(null);
  const [rows, setRows] = useState([]);
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [designationFilter, setDesignationFilter] = useState('');
  const [bandFilter, setBandFilter] = useState('');
  const [sortKey, setSortKey] = useState('efficiency_pct');
  const [banner, setBanner] = useState(null);

  useEffect(() => {
    api.get('/mechanic-kpi/periods').then(r => {
      if (r?.success && r.data?.length) {
        setPeriods(r.data);
        setSelected(r.data[0]);
      } else {
        setLoading(false);
      }
    }).catch(() => setLoading(false));
  }, []);

  const load = useCallback(async () => {
    if (!selected) return;
    setLoading(true);
    try {
      const qs = `period_start=${selected.period_start}&period_end=${selected.period_end}`;
      const r = await api.get(`/mechanic-kpi/snapshots?${qs}`);
      if (r?.success) { setRows(r.data || []); setSummary(r.summary); }
    } catch (e) {
      setBanner({ kind: 'error', text: e?.message || 'Could not load the KPI report.' });
    } finally {
      setLoading(false);
    }
  }, [selected]);

  useEffect(() => { load(); }, [load]);

  const designations = useMemo(
    () => [...new Set(rows.map(r => r.designation).filter(Boolean))].sort(),
    [rows]
  );

  const filtered = useMemo(() => {
    let list = rows;
    if (search.trim()) {
      const q = search.trim().toLowerCase();
      list = list.filter(r => r.mechanic_name.toLowerCase().includes(q) || r.designation?.toLowerCase().includes(q));
    }
    if (designationFilter) list = list.filter(r => r.designation === designationFilter);
    if (bandFilter) {
      list = list.filter(r => {
        const e = Number(r.efficiency_pct);
        if (bandFilter === 'low') return e < 60;
        if (bandFilter === 'mid') return e >= 60 && e < 85;
        return e >= 85;
      });
    }
    return [...list].sort((a, b) => Number(b[sortKey] ?? -1) - Number(a[sortKey] ?? -1));
  }, [rows, search, designationFilter, bandFilter, sortKey]);

  const periodTag = selected ? `${selected.period_start}_to_${selected.period_end}` : 'export';

  const exportExcel = () => {
    if (!filtered.length) return;
    const headers = ['Technician', 'Employee Code', 'Designation', 'Days Present', 'Worked Hrs', 'Billed Value', 'Utilization %', 'Productivity %', 'Efficiency %'];
    const rows = filtered.map(r => [
      r.mechanic_name, r.employee_code, r.designation || '',
      r.days_present, Number(r.worked_hrs).toFixed(1), Number(r.billed_value || 0).toFixed(2),
      Math.round(r.utilization_pct), Math.round(r.productivity_pct), Math.round(r.efficiency_pct),
    ]);
    downloadCsv(`technician-kpi_${periodTag}.csv`, headers, rows);
  };

  const exportPDF = async () => {
    if (!filtered.length) return;
    const doc = new jsPDF();

    // Source PNG is 928x166 (aspect 5.59:1) — a fixed width keeps it sensible
    // across page sizes, matching the same embed pattern used in Reports.jsx.
    let logoHeight = 0;
    try {
      const logoResp = await fetch(pioneerLogoPdf);
      if (logoResp.ok) {
        const bytes = new Uint8Array(await logoResp.arrayBuffer());
        let binary = '';
        for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
        const logoWidthMm = 44;
        logoHeight = logoWidthMm * (166 / 928);
        doc.addImage('data:image/png;base64,' + btoa(binary), 'PNG', 14, 10, logoWidthMm, logoHeight);
      }
    } catch (e) {
      console.warn('Failed to embed the Pioneer logo in the PDF export:', e);
    }

    const margin = 14;
    const titleY = 10 + logoHeight + 10;
    doc.setFontSize(18);
    doc.setTextColor(36, 64, 102);
    doc.text('Technician KPI Report', margin, titleY);
    doc.setFontSize(10);
    doc.setTextColor(100);
    const periodText = selected ? `${fmtDate(selected.period_start)} \u2013 ${fmtDate(selected.period_end)}` : '';
    const generated = `Generated ${new Date().toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' })}`;
    doc.text([periodText, generated].filter(Boolean).join('   \u00b7   '), margin, titleY + 7);

    autoTable(doc, {
      startY: titleY + 12,
      head: [['Technician', 'Designation', 'Days Present', 'Worked Hrs', 'Billed Value', 'U%', 'P%', 'E%']],
      body: filtered.map(r => [
        r.mechanic_name, r.designation || '\u2014', r.days_present,
        Number(r.worked_hrs).toFixed(1), fmtMoney(r.billed_value),
        `${Math.round(r.utilization_pct)}%`, `${Math.round(r.productivity_pct)}%`, `${Math.round(r.efficiency_pct)}%`,
      ]),
      headStyles: { fillColor: [36, 64, 102], fontStyle: 'bold' },
      styles: { fontSize: 8.5 },
      margin: { left: margin, right: margin },
    });

    doc.save(`technician-kpi_${periodTag}.pdf`);
  };

  const cards = summary ? [
    { key: 'count', label: 'Technicians in report', value: summary.technician_count, Icon: Wrench, tone: 'blue' },
    { key: 'billed', label: 'Total billed value', value: fmtMoney(summary.total_billed_value), Icon: DollarCircle, tone: 'green' },
    { key: 'util', label: 'Avg. utilization', value: `${summary.avg_utilization_pct}%`, Icon: Clock, tone: 'amber' },
    { key: 'eff', label: 'Avg. efficiency', value: `${summary.avg_efficiency_pct}%`, Icon: GraphUp, tone: 'rose' },
  ] : [];

  return (
    <div className="page-container cs">
      <header className="cs-head">
        <div>
          <h1 className="cs-title">Technician KPI</h1>
          <p className="cs-sub">
            {selected ? `${fmtDate(selected.period_start)} – ${fmtDate(selected.period_end)}` : 'Attendance, hours and billing performance by technician'}
          </p>
        </div>
        {selected && (
          <div className="cs-actions">
            {periods.length > 1 && (
              <select className="form-control tk-fixed-select"
                value={`${selected.period_start}|${selected.period_end}`}
                onChange={e => {
                  const [ps, pe] = e.target.value.split('|');
                  setSelected(periods.find(p => p.period_start === ps && p.period_end === pe));
                }}>
                {periods.map(p => (
                  <option key={`${p.period_start}|${p.period_end}`} value={`${p.period_start}|${p.period_end}`}>
                    {fmtDate(p.period_start)} – {fmtDate(p.period_end)}
                  </option>
                ))}
              </select>
            )}
            <button type="button" className="cs-btn-ghost" onClick={exportPDF} disabled={!filtered.length}>
              <Page width={15} height={15} /> Export PDF
            </button>
            <button type="button" className="cs-btn-ghost" onClick={exportExcel} disabled={!filtered.length}>
              <Table width={15} height={15} /> Export Excel
            </button>
          </div>
        )}
      </header>

      {banner && <div role="status" className={`cs-banner is-${banner.kind}`}>{banner.text}</div>}

      {!loading && !selected ? (
        <div className="cs-empty" style={{ padding: '48px 20px' }}>
          <Wrench width={40} height={40} />
          <p>No technician KPI report has been imported yet.</p>
        </div>
      ) : (
        <>
          <div className="cs-kpis">
            {cards.map(c => (
              <div className={`cs-kpi cs-kpi--${c.tone}`} key={c.key}>
                <div className="cs-kpi-icon"><c.Icon width={24} height={24} /></div>
                <div className="cs-kpi-body">
                  <p className="cs-kpi-value">{c.value ?? 0}</p>
                  <p className="cs-kpi-label">{c.label}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="cs-controls">
            <div className="cs-search">
              <Search width={17} height={17} />
              <input placeholder="Search technician or designation…" value={search}
                onChange={e => setSearch(e.target.value)} aria-label="Search technicians" />
            </div>
            <select className="form-control tk-fixed-select" value={designationFilter}
              onChange={e => setDesignationFilter(e.target.value)} aria-label="Filter by designation">
              <option value="">All designations</option>
              {designations.map(d => <option key={d} value={d}>{d}</option>)}
            </select>
            <select className="form-control tk-fixed-select" value={bandFilter}
              onChange={e => setBandFilter(e.target.value)} aria-label="Filter by efficiency band">
              <option value="">All efficiency</option>
              <option value="high">High (85%+)</option>
              <option value="mid">Mid (60–84%)</option>
              <option value="low">Low (under 60%)</option>
            </select>
            <select className="form-control tk-fixed-select" value={sortKey}
              onChange={e => setSortKey(e.target.value)} aria-label="Sort by">
              <option value="efficiency_pct">Sort: Efficiency</option>
              <option value="utilization_pct">Sort: Utilization</option>
              <option value="productivity_pct">Sort: Productivity</option>
              <option value="billed_value">Sort: Billed value</option>
              <option value="worked_hrs">Sort: Worked hours</option>
            </select>
            {(designationFilter || bandFilter || search) && (
              <button className="cs-filter-clear" style={{ flex: 'none' }}
                onClick={() => { setDesignationFilter(''); setBandFilter(''); setSearch(''); }}>
                Clear filters
              </button>
            )}
          </div>

          <div className="cs-tablewrap">
            <table className="cs-table cs-table--tasks">
              <thead>
                <tr>
                  <th>Technician</th>
                  <th>Designation</th>
                  <th>Days present</th>
                  <th>Worked hrs</th>
                  <th>Billed value</th>
                  <th>U%</th>
                  <th>P%</th>
                  <th>E%</th>
                </tr>
              </thead>
              <tbody>
                {loading ? (
                  <tr><td colSpan={8} className="cs-empty">Loading…</td></tr>
                ) : filtered.length === 0 ? (
                  <tr><td colSpan={8} className="cs-empty">No technicians match those filters.</td></tr>
                ) : filtered.map(r => {
                  const u = band(r.utilization_pct), p = band(r.productivity_pct), e = band(r.efficiency_pct);
                  return (
                    <tr key={r.id}>
                      <td>
                        <div className="cs-name">{r.mechanic_name}</div>
                        <div className="cs-meta">{r.employee_code}</div>
                      </td>
                      <td className="cs-service">{r.designation}</td>
                      <td>{r.days_present}</td>
                      <td>{Number(r.worked_hrs).toFixed(1)}</td>
                      <td className="cs-service">{fmtMoney(r.billed_value)}</td>
                      <td><span className="cs-pill" style={{ color: u.color, background: u.bg }}>{Math.round(r.utilization_pct)}%</span></td>
                      <td><span className="cs-pill" style={{ color: p.color, background: p.bg }}>{Math.round(r.productivity_pct)}%</span></td>
                      <td><span className="cs-pill" style={{ color: e.color, background: e.bg }}>{Math.round(r.efficiency_pct)}%</span></td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </>
      )}
    </div>
  );
}
